print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 / 4)
print("Integer Division Operator: ")
print(3 // 4)
print(-7 // 2)
print(1 + 2 + 3 * 3)
print((1 + 2 + 3) * 3)
print("Exponentiation Operator: ")
print(2 ** 3)
print("Bitwise XOR Operator: ")
print(10 ^ 11)
print("Modulus Operator: ")
print(5 % 2)
